---
title: "Active Portfolio Management"
subtitle: "Reading Notes"
author: "William Fang"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: 
    toc: true
#  tufte::tufte_book:
#    citation_package: natbib
#    latex_engine: xelatex
#  tufte::tufte_handout:
#    citation_package: natbib
#    latex_engine: xelatex
#ctex: yes
biblio-title: 参考文献
#bibliography: skeleton.bib
link-citations: yes
---

--------------------------------------------------------------------------------

# Chap.1

这章简要介绍了关于主动投资组合管理的基本定律，作者认为未来是属于新生代的**量化主动管理**。^[新生代力量：主动量化管理：它依据严谨的分析和流程来尝试战胜市场，是现代金融经济学研究的近亲。]

随着具备越来越多科学投资理念的新生代投资经理的就任，他们将更多地依靠分析、流程以及结构来取代原来的直觉、建议或者一时之念。这并不意味着英雄式的个人投资洞察力已经成为过去；它意味着投资经理将越来越多地采用系统化的方法来获取和应用他们的洞察力。

> 信息率衡量了主动管理的机会集，它的平方决定了我们产生附加值的能力，信息率越高越好。那么，从哪里寻找更高的信息率呢？

1. 第一个就是我们预测每只资产残差收益率的能力，我们用信息系数（information coefficient, IC）来衡量这种能力，它是收益率的预测值和实现值之间的相关系数。信息系数是衡量我们预测能力的一个度量。

2. 第二个产生高信息率的来源是广度（breadth, BR），即每年我们能够应用上述预测能力的次数。

3. 主动投资组合管理的基本定律告诉我们，信息率正比于我们的预测能力和预测广度的平方根。

    $$ IR = IC \times \sqrt{BR}$$

4. 主动管理即预测，预测是指将资产收益率的原始预测信号转化为精炼预测的过程。这种信息处理在主动管理中至关重要。它的基本想法就是**预测基本定律**：  

    $$ alpha = 波动率 \cdot IC \cdot 标准分值$$
    
**收益、风险、基准、偏好、信息率以及收益率预测是组成主动投资组合管理的基本元素**。


--------------------------------------------------------------------------------

# Chap.2 CAPM

要点：

- 任何股票的收益率都可以分解为系统性（市场）部分和残差部分，这不需要任何经济理论。
- CAPM 要求收益率的残差部分的期望值为 0。
- CAPM 容易理解，也相对容易实施。
- CAPM 背后有一个关于市场有效的强有力的逻辑。
- CAPM 认为被动管理是主动管理的一种低风险的替代选择，使主动基金经理需要证明自己的价值。
- CAPM 为一致预期收益率提供了一个有效的来源。主动投资经理的成功程度将与他的预测优于 CAPM 的一致预测的程度相匹配。
- CAPM 是关于预期收益率而非风险的。


## 收益率分解

我们定义一个有投资组合的 $\beta_P$ 为
$$
\beta_P = \frac{Cov(r_P, r_M)}{Var(r_M)}
$$

$\beta$ 正比于投资组合收益率与市场收益率之间的协方差，它是对未来的一个预测。^[这里需要注意的是，市场组合的 $\beta$ 按照定义等于 1, 无风险资产的 $、beta$ 等于 0。]

从数据的角度来看，投资组合的 $\beta_p$ 来自**线性回归**的估计，这个回归方程为：

$$
r_{P,t} = \alpha_p + \beta_P \cdot r_{M,t} + \epsilon_{P,t}
$$
我们把估计得到的参数，$\hat{\alpha_P}$ 和 $\hat{\beta_P}$ 称为**历史的（或者实现）的值**。

$\beta$ 是一种将风险和收益率分解为两部分的工具。如果我们知道一个组合的 $\beta$，就可以将它的**超额收益率**分解为**市场部分**和**残差部分**：

$$
r_P = \beta_P \cdot r_M + \theta_P
$$
如果我们假定残差收益率 $\theta_P$ 与市场收益率 $r_M$ 是不相关的，那么，投资组合的方差就可以分解为

$$
\sigma_P^2 = \beta_P^2 \cdot \sigma_M^2 + \omega_P^2
$$
其中，$\omega_P^2$ 是残差收益率 $\theta_P$ 的方差。


> $\beta$ 能够使我们将任意投资组合的超额收益率分解为两个不相关的部分，一个是市场部分，另一个是残差部分。


## CAPM 假定预期残差收益率为零

在预期残差收益率为零的假设下，即 $E\big[ \theta_P \big] = 0$，则推出，投资组合的预期超额收益率完全由市场的预期超额收益率和投资组合与市场的 $\beta$ 共同决定，

$$
E\big[ r_P \big] = \beta_P \cdot E\big[ r_m \big] = \beta \cdot \mu_M
$$

> 在 CAPM 模型下，任何投资组合的预期残差收益率为零，投资组合的超额收益率与 $\beta$ 成正比关系。


--------------------------------------------------------------------------------


# Chap.3 风险

## 投资组合的风险与方差

对于任何两只股票，如果二者收益率之间的相关系数为 $\rho$， 那么一个包含 $N$ 只股票的投资组合，其风险（标准差）为

$$
\sigma_P = \sigma \cdot \sqrt{\frac{1 + \rho \cdot (N-1) }{N}}
$$

特别的，对于独立不相关的股票的投资组合，我们有 $\rho = 0$, 即得到

$$
\sigma_P = \frac{\sigma}{\sqrt{N}}
$$
而当 $\rho \neq 0$ 时，随着投资组合数量 $N$ 的增加，我们会得到

$$
\sigma_P \rightarrow \sigma \cdot \sqrt{\rho}
$$

这里，我们可以推导出计算**年化标准差**的方法。这样想：^[一般的，我们先计算日内的夏普比率，然后乘以$\sqrt{252}$得到年化的夏普比率。]

> 风险既不能沿着横截面也不能沿着时间序列相加，但是方差可以沿着时间序列相加，如果任意不重叠的两段时期上的收益率是不相同的。事实上，对于大多数资产类型而言，其前后两段不重叠时期上的收益率之间的相关系，即自相关关系，都是接近于 0 的。**这意味着，方差随着预测期的长度增长，而风险则随着预测期长度的平方根增长**。

$$
\sigma_{annualized} = \sigma_{daily} \cdot \sqrt{252} 
$$


## 跟踪误差

$$
\varphi = Std\big| r_P - r_B \big|
$$
我们称之为主动管理的**跟踪误差**，描述了组合对业绩基准的波动情况。


## 风险模型

我们需要估计任意两只股票之间的相关系数矩阵，即**协方差矩阵**

$$
\mathbf{V} = \begin{bmatrix}
\sigma_{1}^2   & \sigma_{1,2}^2 & \cdots & \sigma_{1,N}^2 \\
\sigma_{2,1}^2 & \sigma_{2}^2   & \cdots & \sigma_{2,N}^2 \\
\vdots         & \cdots         & \vdots & \cdots         \\
\sigma_{N,1}^2   & \sigma_{N,2}^2 & \cdots & \sigma_{N}^2
\end{bmatrix}
$$
其中，我们有 $\sigma_{i,j} = \sigma{j,i}$。协方差矩阵包含了我们需要计算投资组合层面的风险所不要的所有资产层面的风险信息。风险模型的目标就是要紧缺并高效地预测协方差矩阵。协方差矩阵中包含太多的独立参数，这使得建立风险模型的任务极具挑战性。



### 单因子模型

单因子模型是 CAPM 的雏形，但二者仍有不同。单因子模型首先将收益率分解为

$$
r_n = \beta_n \cdot r_M + \theta_n
$$
其中 $\beta_n$ 是股票 $n$ 的估计值， $\theta_n$ 这是残差收益率。单因子模型假设残差收益率之间相互不相关，因此推出

$$
Cov\big( r_n, r_m \big) = \beta_n \cdot \beta_m \cdot \sigma_M^2 \\
\sigma_n^2 = \beta_n^2 \cdot \sigma_M^2 + \omega_n^2
$$



### 相关系数模型

该模型假设

$$
Cov\big( r_n,r_m \big) = \sigma_n \cdot \sigma_m \cdot \rho
$$


### 历史样本模型

这依赖于历史数据的样本方差和样本协方差。


## 结构化多因子风险模型

结构化多因子模型基于如下假设：股票的收益率可以被一组共同因子和一个仅与该股票有关的特异因子所解释．我们可以把这些共同因子看作是影响一组股票价格变动的作用力．这组股票可以是银行行业的全部股票，或者具有高财务杠杆的全部股票，或是所有市值较小的股票．如此等等。

结构化风险模型对收益率进行线性分解，

$$
r_{n,t} = \sum_k X_{n,t}^{(k)} \cdot b_t^{(k)} + u_{n,t}^{(k)}
$$
整个市场的风险结构为

$$
\mathbf{V_{n,m}} = \sum_{k_1,k_2 = 1}^K X_{n}^{(k_1)} \cdot \mathbf{F}_{k_1,k_2} \cdot X_{m,K_2} + \mathbf{\Delta_{n,m}}
$$

- $\mathbf{V_{n,m}}$：资产 n 和资产 m 的协方差矩阵， 当 $n=m$ 时，则退变为方差矩阵。
- $X_{n}^{(k_1)}$：资产 n 对因子 $k_1$ 的暴露度
- $\mathbf{F}_{k_1,k_2}$：因子 $k_1$ 和因子 $k_2$ 之间的收益率协方差
- $\mathbf{\Delta_{n,m}}$：资产 n 和资产 m 之间的特异协方差，并且有 $\mathbf{\Delta_{n,m}} = \mathbf{0}$


--------------------------------------------------------------------------------

# Chap.4 超常收益率

$$
E\big[ r_n \big] = i_f + \beta_n \cdot \mu_B + \beta_n \cdot \Delta f_n + \alpha_n
$$

- $i_f$: 无风险收益率，即时间价值
- $\beta_n \cdot \mu_B$: 相对于业绩基准的风险溢价
- $\beta_n \cdot \Delta f_n$: 超常业绩基准的收益率
- $\alpha_n$: 预期残差收益率，$\alpha_n = E\big[ \theta_n \big]$























